src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: OperationRepository::class)]
#[Vich\Uploadable]
class Operation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'zipFile', fileNameProperty: 'global_zip', size: 'zipSize')]
    #[Assert\File(
        maxSize: '1024M',
        mimeTypes: ['application/zip', 'application/pdf'],
        mimeTypesMessage: 'Veuillez télécharger un fichier de type ZIP ou PDF'
    )]
    private ?File $zipFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $global_zip = null;

    #[ORM\Column(nullable: true)]
    private ?int $zipSize = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'operation_visuel', fileNameProperty: 'visuel', size: 'imageSize')]
    #[Assert\File(
        maxSize: '2M',
        mimeTypes: ['image/jpeg', 'image/png'],
        mimeTypesMessage: 'Veuillez télécharger un fichier image valide (jpg, png)'
    )]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255)]
    private ?string $visuel = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $uploadTimestamp = null;

    #[ORM\OneToMany(mappedBy: 'operation', targetEntity: Outil::class, cascade: ['persist','remove'])]
    private Collection $outils;

    #[ORM\ManyToOne(inversedBy: 'operations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie = null;

    #[ORM\ManyToMany(targetEntity: Marque::class, inversedBy: 'operations')]
    private Collection $marques;

    #[ORM\Column]
    private ?bool $alaune = null;

    #[ORM\OneToMany(mappedBy: 'outil', targetEntity: StatUser::class, cascade: ['remove'])]
    private Collection $statUsers;



    public function __construct()
    {
        $this->outils = new ArrayCollection();
        $this->marques = new ArrayCollection();
        $this->statUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }




    /**
     * @return Collection<int, Outil>
     */
    public function getOutils(): Collection
    {
        return $this->outils;
    }

    public function addOutil(Outil $outil): self
    {
        if (!$this->outils->contains($outil)) {
            $this->outils->add($outil);
            $outil->setOperation($this);
        }

        return $this;
    }

    public function removeOutil(Outil $outil): self
    {
        if ($this->outils->removeElement($outil)) {
            // set the owning side to null (unless already changed)
            if ($outil->getOperation() === $this) {
                $outil->setOperation(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function setVisuel(?string $visuel): self
    {
        $this->visuel = $visuel;
        return $this;
    }
    public function getVisuel(): ?string
    {
        return $this->visuel;
    }




    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function __toString(): string
    {
        return $this->titre;
    }

    /**
     * @return Collection<int, Marque>
     */
    public function getMarques(): Collection
    {
        return $this->marques;
    }

    public function addMarque(Marque $marque): self
    {
        if (!$this->marques->contains($marque)) {
            $this->marques->add($marque);
            $marque->addOperation($this);
        }

        return $this;
    }

    public function removeMarque(Marque $marque): self
    {
        if ($this->marques->removeElement($marque)) {
            $marque->removeOperation($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


   public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }



    public function setZipFile(?File $zipFile = null): void
    {
        $this->zipFile = $zipFile;

        if (null !== $zipFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->uploadTimestamp = new \DateTimeImmutable();
        }
    }

    public function getZipFile(): ?File
    {
        return $this->zipFile;
    }



    public function getGlobalZip(): ?string
    {
        return $this->global_zip;
    }

    public function setGlobalZip(?string $global_zip): self
    {
        $this->global_zip = $global_zip;
        return $this;
    }


    public function getUploadTimestamp(): \DateTimeInterface
    {
        return $this->uploadTimestamp;
    }


    public function setZipSize(?int $zipSize): void
    {
        $this->zipSize = $zipSize;
    }

    public function getZipSize(): ?int
    {
        return $this->zipSize;
    }

    public function isAlaune(): ?bool
    {
        return $this->alaune;
    }

    public function setAlaune(bool $alaune): self
    {
        $this->alaune = $alaune;

        return $this;
    }

    /**
     * @return Collection<int, StatUser>
     */
    public function getStatUsers(): Collection
    {
        return $this->statUsers;
    }

    public function addStatUser(StatUser $statUser): self
    {
        if (!$this->statUsers->contains($statUser)) {
            $this->statUsers->add($statUser);
            $statUser->setOperation($this);
        }

        return $this;
    }

    public function removeStatUser(StatUser $statUser): self
    {
        if ($this->statUsers->removeElement($statUser)) {
            // set the owning side to null (unless already changed)
            if ($statUser->getOperation() === $this) {
                $statUser->setOperation(null);
            }
        }

        return $this;
    }





}

src/Controller/DefaultController.php
<?php
namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Operation;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class DefaultController extends AbstractController
{
    #[Route('/', name:'homepage')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        // usually you'll want to make sure the user is authenticated first,
        // see "Authorization" below
        //$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // returns your User object, or null if the user is not authenticated
        // use inline documentation to tell your editor your exact User class
        /** @var \App\Entity\User $user */

        $user = $this->getUser();

        $operations = [];

        $categorieRepository = $entityManager->getRepository(Categorie::class);
        $operationRepository = $entityManager->getRepository(Operation::class);

        $categories = $categorieRepository->findAll();
        foreach ($categories as $category) {
            $operations[$category->getTitre()] = $operationRepository->findByCategorie($category);
        }
        $operationAlaune = $operationRepository->findOneBy(['alaune'=> true]);


        return $this->render('default/index.html.twig', [
            'user' => $user,
            'operations' => $operations,
            'opeAlaune' => $operationAlaune
        ]);
    }


}

templates/default/index.html.twig
{# app/Resources/views/index.html.twig #}

{% extends 'base.html.twig' %}
{%  set bodyClass = 'index' %}
{% block menu %}
    <div class="menu">
        {% for cat, operationsInCat in operations %}
            {% if operationsInCat|length >0 %}
                <span class="menuCat" data-cat="{{ cat | replace({ 'è':'e', 'é':'e', 'ê':'e', ' ':'-' }) }}">{{ cat|upper }}</span>
            {% endif %}
        {% endfor %}
    </div>
{%  endblock %}
{% block body %}
    <section class="categories">
        <div id="operations-items">
            {% for cat, operationsInCat in operations %}
                {% if operationsInCat|length >0 %}
                <div class="categorie" id="{{ cat | replace({ 'è':'e', 'é':'e', 'ê':'e', ' ':'-' })}}">
                    <h2>{{ cat }}</h2>
                    <div class="operations">
                        {% for ope in operationsInCat %}
                            <div class="operation-item">
                                <a href="/operation/{{ ope.slug }}">
                                    <figure>
                                        <img src="{{ asset(image_dir ~ 'operations/' ~ ope.visuel) | imagine_filter('slide')  }}"alt="{{ ope.titre }}"/>
                                    </figure>
                                </a>
                                <strong>{{ ope.titre }}</strong><br>
                                {% if ope.dateDebut|date('Y') != '1970' or ope.dateFin|date('Y') != '2100' %}
                                    <span class="gris">{% if ope.dateDebut|date('Y') != '1970' %}{{ ope.dateDebut|date('d/m') }} {% else  %}... {% endif %} >
                                    {% if ope.dateFin|date('Y') != '2100' %}{{ ope.dateFin|date('d/m') }} {% else  %}...{% endif %}</span>
                                {%  endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% if opeAlaune %}
        <div class="nouveaute">
            <h2>Nouveauté</h2>
            <a href="/operation/{{ opeAlaune.slug }}" class="alaune">
                <figure >
                    <img src="{{ asset(image_dir ~ 'operations/' ~ opeAlaune.visuel) | imagine_filter('slide')  }}"alt="{{ opeAlaune.titre }}"/>
                </figure>
                <div class="bloc">

                    <div class="title_dates">
                        <h4>{{ opeAlaune.titre }}</h4><br>
                        <div class="dates">
                            <span class="smallcaps">du</span><br>{{ opeAlaune.dateDebut|date('d/m') }}<br>
                            <span class="smallcaps">au</span><br>{{ opeAlaune.dateFin|date('d/m') }}
                        </div>

                    </div>
                    <div class="marques">
                        {% for marque in opeAlaune.marques %}
                            <figure class="logo">
                                <img src="{{ asset(image_dir ~ 'marques/' ~ marque.logo)   }}"alt="{{ marque.nom }}"/>
                            </figure>
                        {% endfor %}
                    </div>

                </div>
            </a>
        </div>
        {% endif %}
    </section>
{% endblock %}

templates/default/operation.html.twig
{# app/Resources/views/index.html.twig #}

{% extends 'base.html.twig' %}
{%  set bodyClass = 'operation' %}
{% block menu %}
    <div class="menu">
        {% for cat, operationsInCat in operations %}
            {% if operationsInCat|length >0 %}
                <a class="menuCat" href="/#{{ cat | replace({ 'è':'e', 'é':'e', 'ê':'e', ' ':'-' }) }}">{{ cat|upper }}</a>
            {% endif %}
        {% endfor %}
    </div>
{%  endblock %}
{% block body %}
    <section class="operation">
        <div class="container">
            <small>
                <a href="/">
                    <span class="icon-text">
                      <span class="icon">
                        <ion-icon name="home-sharp"></ion-icon>
                      </span>
                      <span>Accueil</span>
                    </span>
                </a>&nbsp; > &nbsp;{{ ope.categorie }} > <strong>{{ ope.titre }}</strong></small>
            <figure class="cover">
                <img src="{{ asset(image_dir ~ 'operations/' ~ ope.visuel) | imagine_filter('operation_cover')  }}"alt="{{ ope.titre }}"/>
            </figure>
            <div class="operation">
                <div class="desc">
                    <h1>{{ ope.titre }}</h1>
                    <div class="description">{{ ope.description | raw }}</div>
                </div>
                <div class="bloc">
                    {% if ope.dateDebut|date('Y') != "1970" or ope.dateFin|date('Y') != '2100' %}
                    <div class="title_dates">
                        <div class="dates">
                            {% if ope.dateDebut|date('Y') != '1970' %}
                                <span class="smallcaps">du</span><br>{{ ope.dateDebut|date('d/m') }}<br>
                            {% endif %}
                            {% if ope.dateFin|date('Y') != '2100' %}
                                <span class="smallcaps">au</span><br>{{ ope.dateFin|date('d/m') }}
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}

                    <div class="marques">
                        {% for marque in ope.marques %}
                            <figure class="logo">
                                <img src="{{ asset(image_dir ~ 'marques/' ~ marque.logo)   }}"alt="{{ marque.nom }}"/>
                            </figure>
                        {% endfor %}
                    </div>
                    {% if ope.globalZip %}
                    <a class="file"
                       href="{{ asset(files_dir) ~ ope.id ~'/' ~ope.uploadTimestamp|date('Ymd') ~ '/' ~ ope.globalZip }}"
                       target="_blank"
                       data-operation="{{ ope.titre }}"
                       data-user="{{ user.username }}"
                       download>
                        <span class="icon-text">
                          <span class="icon">
                            <ion-icon name="download-outline"></ion-icon>
                          </span>
                            <span>Téléchargez tous les outils</span>
                        </span>
                    </a>
                    {%  endif %}
                </div>

            </div>


            <div class="outils">
                {% for outil in ope.outils %}
                    <div class="outil">
                        <div class="slide">
                            <figure>
                                {% if outil.visuel %}
                                <img src="{{ asset(image_dir ~ 'outils/' ~ outil.visuel) | imagine_filter('slide_no_crop')  }}"  alt="{{ outil.titre }}"/>
                                {% else %}
                                <img src="{{ asset(image_dir ~ 'operations/' ~ ope.visuel) | imagine_filter('slide_no_crop')  }}"  alt="{{ outil.titre }}"/>
                                {% endif %}
                            </figure>
                        </div>

                        <div class="content">
                            <h3>{{ outil.titre }}</h3>
                            <div>{{ outil.description | raw}}</div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}